{% set name = "Flask-SeaSurf" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/maxcountryman/flask-seasurf/archive/{{ version }}.tar.gz
  sha256: d0f76af8abd993ca3dcb6d2065fa242900c2078bf0fb70cb81a17eba0b6b0705

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - flask

test:
  imports:
    - flask_seasurf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/maxcountryman/flask-seasurf/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An updated CSRF extension for Flask.
  doc_url: https://flask-seasurf.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
